### ISSUE TITLE
Support for MKR ETH not documented

### ISSUE THREAD

**Issue by baqwas** [arduino-libraries/Arduino_ConnectionHandler#40]
Hello!

Is there any equivalent statement for the MKR ETH shield for the MKR1000 WiFi mode:

`WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);`

Need to use MKR1000 with already tested MKR ETH shield. Thanks.

Kind regards.

**Comment by aentinger** [comment]
Good Morning :wave: ☕ 
Currently there is no support for ethernet via e.g. MKR ETH shield, it should not be too hard to add though. Do you think you could prepare a PR for this? I'll be available for guidance, testing and merging.
Cheers, Alex

**Comment by baqwas** [comment]
Hello @aentinger,

Thank you for looking into this topic. I will gladly prepare something for you in as much detail as I can provide (with the obvious interest in seeing a future solution). I understand the prevailing priorities that may be imposed upon you owing to the popularity of some of the other options.

Please allow me a day or two to DRAFT something. In the interim if you have any suggestion/template please let me know; I'm truly a novice in matters related to GitHub. Thanks again.

Kind regards.

**Comment by aentinger** [comment]
That sounds great :rocket: Meanwhile I've gotten myself 2 MKR ETH shields for testing :wink:

**Comment by baqwas** [comment]
[Arduino PR Cloud MKR ETH library.docx](https://github.com/arduino-libraries/Arduino_ConnectionHandler/files/5146341/Arduino.PR.Cloud.MKR.ETH.library.docx)

Hello @aentinger,

The attachment is my 1st DRAFT. Please correct me if I am not on the right track. Thanks again for all your help and guidance.

Kind regards.

**Comment by aentinger** [comment]
Hi @baqwas :wave: :coffee: 

Thank you very much for your detailed request and reasoning behind your desire to have Ethernet support for Arduino IoT Cloud ;) I've got to be honest, I was rather expecting a code contribution but all in all it should not be too difficult to extend `Arduino_ConnectionHandler` for the Ethernet shield. Let me prepare a small PR and maybe you can help me by testing it?

Cheers, Alex

**Comment by baqwas** [comment]
Hello @aentinger,

Thanks for the super fast turnaround. As I had mentioned previously, I am a _total_ newbie with GitHub operations (that is why I completely misunderstood your acronym PR). I can follow your instructions with some more details, please. Thanks for your patience.

What you have described will work very nicely for me if I can have access to the **Arduino_EthernetConnectionHandler** .cpp and .h files, please. Which branch do I need to clone? Thanks for your understanding.

Kind regards.

**Comment by aentinger** [comment]
Hi,
The work-in-progress code for adding Ethernet support to `Arduino_ConnectionHandler` is to be found [here](https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/41).

If you use this [link](https://github.com/arduino-libraries/Arduino_ConnectionHandler/archive/ethernet.zip) you directly download the version including the `Arduino_EthernetConnectionHandler` source files and store it at your Arduino installation library folder.

What board are you typically using for this? It must be a MKR ZERO because all other MKR boards have some form of connectivity and you just need Ethernet - am I right?

**Comment by aentinger** [comment]
@baqwas I've not heard from you anymore but your wish has been partially implemented in #41. I'm therefore closing this issue and suggest to continue the discussion over there.
