### ISSUE TITLE
Trouble Dropping GSM Connection With No Recovery

### ISSUE THREAD

**Issue by PhysicsUofRAUI** [arduino-libraries/Arduino_ConnectionHandler#60]
I have been having trouble with the Arduino MKR GSM dropping the connection to the Arduino IoT cloud and not being able to recover.

I was thinking that it must be the connection to the antenna, so I tried putting dielectric grease on the connection of the antenna. That seemed to help, but I still have had a few times the connection has dropped and failed to reconnect. 

I am thinking it is similar to this issue: https://github.com/arduino-libraries/MKRGSM/issues/66.

I think it might be fixed by adding 
```
static int const GPRS_TIMEOUT = 30000;
```

to the constants in src\Arduino_GSMConnectionHandler.cpp, and then

```
_gprs.setTimeout(GPRS_TIMEOUT);
```

directly under

```
_gsm.setTimeout(GSM_TIMEOUT);
```

In the implementation of GSMConnectionHandler::update_handleInit() in the same file as mentioned before. 

This is what I am planning to try anyways. 

I am not that experienced with regards to GSM communication, so if someone has a better idea to try and fix the problem I've been having I'd like to hear it.

**Comment by PhysicsUofRAUI** [comment]
Adding the two lines of code is working for me at the moment. I am currently running two MKR GSM units in different locations doing different things. One unit is in an area with good cell service and the other one has bad cell service. If they both run without outside intervention for the next two weeks I am going to guess that this was the problem.

Could the library be changed to either let the user set these timeouts, or so that this timeout is set the way I set it. 

I would be willing to make a pull request for this.

**Comment by aentinger** [comment]
Hi @PhysicsUofRAUI :wave: :coffee: 
Thank you very much for your observation. Would you be willing to supply a PR with - for a start - internally defined timeouts?

**Comment by per1234** [comment]
Closing as fixed by https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/61

Based on comment here:
https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/61#issuecomment-847520378
