### ISSUE TITLE
Why no SSL Client Support ?

### ISSUE THREAD

**Issue by Twinkle299** [arduino-libraries/Arduino_ConnectionHandler#95]
I am using this along with the arduino mqtt library and its all working well however i now need to connect to an mqtt broker using TLS, i was surprised to find that i cannot use this connection handler library for that, are there are plans to add support this functionality ?

**Comment by pennam** [comment]
@Twinkle299 which board are you using? To add SSL capabilities to the ConnectionHandler Client you can use this 
 libraries:
 - https://github.com/arduino-libraries/ArduinoBearSSL
 - https://github.com/arduino/ArduinoCore-renesas/tree/main/libraries/SSLClient
 - https://github.com/govorox/SSLClient
